### PR TITLE
Corrections for french and english

### PR DESCRIPTION
**Pull request by LFavier**
Thanks for the very useful plugin !
I have provided some corrections for phrases, but no modification of code function.

### CODE REVIEW

**Comment by Shnoulle** [comment]
Thank you, i look at this :)

**Comment by LFavier** [comment]
Actually I've found a small bug (not corrected in this pull request) :
In your cpVille.php file you use "version_compare" twice (lines 380 & 385) with the third parameter ">= ".
The space after the sign causes an exception.

**Comment by Shnoulle** [comment]
> Actually I've found a small bug (not corrected in this pull request) : 
> In your cpVille.php file you use "version_compare" twice (lines 380 & 385) with the third parameter ">= ". 
> The space after the sign causes an exception.

PHP version dependent ?

**Comment by Shnoulle** [comment]
https://github.com/SondagesPro/LS-cpVille/commit/b22b6c398a5a78a844fae81a88c5367a2304d563

**Comment by Shnoulle** [comment]
https://gitlab.com/SondagesPro/QuestionSettingsType/cpVille/-/commit/b22b6c398a5a78a844fae81a88c5367a2304d563

**Pull request merged**
